run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  max-same-issues: 100
  exclude-dirs:
    - local
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - errcheck
        - gosec
  fix: true

linters:
  enable:
    - bodyclose
    - copyloopvar
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  path-prefix: ""
  sort-results: true
